config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :channels do
    resource :channel_user
    resources :messages
  end

  namespace :admin do
    resources :users
    resources :announcements
    resources :notifications
    resources :services
    resources :channels
    resources :messages

    root to: "users#index"
  end
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end


  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'register', to: 'devise/registrations#new'
    delete 'logout', to: 'devise/sessions#destroy'
  end
  devise_for :users, controllers: { registrations: "registrations", omniauth_callbacks: "users/omniauth_callbacks" }
  
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/channel.rb
class Channel < ApplicationRecord
  has_many :channel_users, dependent: :destroy
  has_many :users, through: :channel_users
  has_many :messages, dependent: :destroy

  validates :name, presence: true
end

app/controllers/admin/channels_controller.rb
module Admin
  class ChannelsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_channel, only: [:show, :edit, :update, :destroy]

  # GET /channels
  # GET /channels.json
  def index
    @channels = Channel.all
  end

  # GET /channels/1
  # GET /channels/1.json
  def show
    @channel_user = current_user.channel_users.find_by(channel: @channel)
    @last_read_at = @channel_user&.last_read_at || @channel.created_at
    @channel_user&.touch(:last_read_at)
    
  end

  # GET /channels/new
  def new
    @channel = Channel.new
  end

  # GET /channels/1/edit
  def edit
  end

  # POST /channels
  # POST /channels.json
  def create
    @channel = Channel.new(channel_params)

    respond_to do |format|
      if @channel.save
        format.html { redirect_to @channel, notice: 'Channel was successfully created.' }
        format.json { render :show, status: :created, location: @channel }
      else
        format.html { render :new }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /channels/1
  # PATCH/PUT /channels/1.json
  def update
    respond_to do |format|
      if @channel.update(channel_params)
        format.html { redirect_to @channel, notice: 'Channel was successfully updated.' }
        format.json { render :show, status: :ok, location: @channel }
      else
        format.html { render :edit }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /channels/1
  # DELETE /channels/1.json
  def destroy
    @channel.destroy
    respond_to do |format|
      format.html { redirect_to channels_url, notice: 'Channel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_channel
      @channel = Channel.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def channel_params
      params.require(:channel).permit(:name)
    end
end

app/helpers/channels_helper.rb
module ChannelsHelper
  def active_channel?(channel)
    channel == @channel
  end
end

app/views/channels/_form.html.erb
<%= form_with(model: channel, local: true) do |form| %>
  <% if channel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(channel.errors.count, "error") %> prohibited this channel from being saved:</h2>

      <ul>
      <% channel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <% if channel.persisted? %>
      <div class="float-right">
        <%= link_to 'Destroy', channel, method: :delete, class: "text-danger", data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>

    <%= form.submit class: 'btn btn-primary' %>
    <%= link_to "Cancel", anchor: "wall", class: "btn btn-link" %>
    
  </div>
<% end %>

app/views/channels/edit.html.erb
<h1>Edit Channel</h1>

<%= render 'form', channel: @channel %>

app/views/channels/index.html.erb
<div class="channelsIndex">
  
    
    <h1 class="text-light">Channels</h1>
  

   
    <%= link_to new_channel_path, class: 'btn btn-warning' do %>
      Add New Channel
    <% end %>
    
  

  <div class="table-responsive">
    <table class="table table-striped table-bordered table-hover tabla">
      <thead>
        <tr>
      
          <th>Name</th>
      

              
        </tr>
      </thead>

      <tbody>
        <% @channels.each do |channel| %>
          <%= content_tag :tr, id: dom_id(channel), class: dom_class(channel) do %>
            
              <td><i class="fas fa-sign-in-alt not-show"></i>
              <%= link_to channel.name, channel, class: "textOr" %></td>
            

            
            
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/channels/new.html.erb
<h1>New channel</h1>

<%= render 'form', channel: @channel %>

app/views/channels/new.js.erb
$('#newModal').modal('show')

app/views/channels/show.html.erb
<!-- Modal -->
<div class="modal fade" id="newModal" tabindex="-1" aria-labelledby="newModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="newModalLabel">New Channel</h5>
      
      </div>
      <div class="modal-body">
      <%= render 'form', channel: Channel.new %>
      </div>
      
    </div>
  </div>
</div>
<div class="row showContainer" data-controller="channel" data-channel-id="<%= @channel.id %>">
  <div class="col-sm-2 sidebar">
    <%= render "shared/sidebar" %>
  </div>

  <div class="col-sm-9 relativee">
    <div class="d-flex justify-content-between sticky-top bg-white border-bottom pt-2">
      <h2><strong>#<%= @channel.name %></strong></h3>

      <div>
        <%= link_to "Leave", channel_channel_user_path(@channel), method: :delete, class: "linkk btn btn-link" %>
      </div>
    </div>

    <div data-target="channel.messages" class="bg-white messageB">
      <%= render @channel.messages %>
    </div>

  </div>

  <div class="fixed-bottom row">
    
      <% if current_user.channels.include?(@channel) %>
      <div class="col-sm-9 offset-sm-2 p-2 bg-white" >
        <%= form_with model: [@channel, Message.new], data: { action: "ajax:success->channel#clearMessage" } do |form| %>
          <%= form.text_field :body, placeholder: "Message ##{@channel.name}", class: "form-control", data: { target: "channel.newMessage" } %>
        <% end %>
      </div>  

      <% else %>
      <div class="joinLink offset-sm-2">
          <%= link_to "Join #{@channel.name}", channel_channel_user_path(@channel), method: :post, class: 'linkRed' %>
      </div>
      <% end %>
      
  </div>
</div>